language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-get install libpthread-stubs0-dev libgl1-mesa-dev libx11-dev
  - sudo apt-get install libxrandr-dev libfreetype6-dev libglew1.5-dev
  - sudo apt-get install libjpeg8-dev libgpgme11-dev libsndfile1-dev libopenal-dev
  - sudo apt-get install libjpeg62-dev
  - sudo apt-get install libzip-dev
  - wget http://www.sfml-dev.org/download/sfml/2.1/SFML-2.1-linux-gcc-64bits.tar.bz2
  - tar xf SFML-2.1-linux-gcc-64bits.tar.bz2
  - sudo cp -r SFML-2.1/lib/* /usr/local/lib/.
  - sudo cp -r SFML-2.1/include/* /usr/local/include/.
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.7
  - export CXX=g++-4.7
  - export CC=gcc-4.7
script:
  - mkdir build
  - cd build
  - cmake ../src/
  - make -j 4
